'use client'

import { useEffect, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { ArrowLeft, ArrowRight, Play, Eye, Terminal, FolderTree, FileCode, ChevronRight, ChevronDown, Loader2, AlertCircle } from 'lucide-react'
import Link from 'next/link'
import { getProjectConfig } from '@/app/actions/pipeline'
import type { GeneratedConcept } from '@/app/actions/pipeline'

interface FileNode {
  name: string
  type: 'file' | 'folder'
  children?: FileNode[]
  content?: string
}

export default function DevDudePage() {
  const searchParams = useSearchParams()
  const projectId = searchParams.get('project')

  const [project, setProject] = useState<{ name: string; generated_concept: GeneratedConcept | null } | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const [selectedFile, setSelectedFile] = useState<string | null>(null)
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set(['src', 'src/app']))
  const [terminalOutput, setTerminalOutput] = useState<string[]>([
    '$ npm run dev',
    'Ready - started server on http://localhost:3000',
    '✓ Compiled successfully',
    '$'
  ])
  const [isRunning, setIsRunning] = useState(false)

  // Generate file tree based on project concept
  const generateFileTree = (concept: GeneratedConcept | null): FileNode[] => {
    if (!concept) return []

    return [
      {
        name: 'src',
        type: 'folder',
        children: [
          {
            name: 'app',
            type: 'folder',
            children: [
              { name: 'layout.tsx', type: 'file', content: generateLayoutCode() },
              { name: 'page.tsx', type: 'file', content: generateHomeCode() },
              ...concept.pages.map(page => ({
                name: page.route.split('/').pop() || 'page',
                type: 'folder' as const,
                children: [{ name: 'page.tsx', type: 'file' as const, content: generatePageCode(page) }]
              }))
            ]
          },
          {
            name: 'components',
            type: 'folder',
            children: concept.pages.flatMap(page =>
              page.components.map(comp => ({
                name: `${comp}.tsx`,
                type: 'file' as const,
                content: generateComponentCode(comp)
              }))
            ).slice(0, 10) // Limit for display
          },
          {
            name: 'lib',
            type: 'folder',
            children: [
              { name: 'supabase.ts', type: 'file', content: generateSupabaseCode() },
              { name: 'utils.ts', type: 'file', content: generateUtilsCode() }
            ]
          }
        ]
      },
      { name: 'package.json', type: 'file', content: generatePackageJson() },
      { name: 'tailwind.config.ts', type: 'file', content: '// Tailwind configuration...' },
      { name: '.env.local', type: 'file', content: 'NEXT_PUBLIC_SUPABASE_URL=\nNEXT_PUBLIC_SUPABASE_ANON_KEY=' }
    ]
  }

  const generateLayoutCode = () => `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: '${project?.name || 'App'}',
  description: 'Generated by DevDudes',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`

  const generateHomeCode = () => `export default function Home() {
  return (
    <main className="min-h-screen p-8">
      <h1 className="text-4xl font-bold">
        Welcome to ${project?.name || 'Your App'}
      </h1>
    </main>
  )
}`

  const generatePageCode = (page: { name: string; components: string[] }) => `import { ${page.components.join(', ')} } from '@/components'

export default function ${page.name.replace(/\s/g, '')}Page() {
  return (
    <div className="space-y-6 p-6">
      <h1 className="text-2xl font-bold">${page.name}</h1>
      ${page.components.map(c => `<${c} />`).join('\n      ')}
    </div>
  )
}`

  const generateComponentCode = (name: string) => `'use client'

export function ${name}() {
  return (
    <div className="rounded-lg border p-4">
      <h2 className="font-semibold">${name}</h2>
      {/* Component content */}
    </div>
  )
}`

  const generateSupabaseCode = () => `import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

export const supabase = createClient(supabaseUrl, supabaseKey)`

  const generateUtilsCode = () => `import { clsx, type ClassValue } from 'clsx'
import { twMerge } from 'tailwind-merge'

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}`

  const generatePackageJson = () => `{
  "name": "${project?.name?.toLowerCase().replace(/\s/g, '-') || 'app'}",
  "version": "0.1.0",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "^15.0.0",
    "react": "^19.0.0",
    "@supabase/supabase-js": "^2.0.0"
  }
}`

  useEffect(() => {
    async function loadProject() {
      if (!projectId) {
        setIsLoading(false)
        return
      }

      const result = await getProjectConfig(projectId)
      if (!result.error && result.data) {
        setProject({
          name: result.data.name,
          generated_concept: result.data.generated_concept as unknown as GeneratedConcept
        })
      }
      setIsLoading(false)
    }
    loadProject()
  }, [projectId])

  const fileTree = generateFileTree(project?.generated_concept || null)

  const toggleFolder = (path: string) => {
    const newExpanded = new Set(expandedFolders)
    if (newExpanded.has(path)) {
      newExpanded.delete(path)
    } else {
      newExpanded.add(path)
    }
    setExpandedFolders(newExpanded)
  }

  const findFileContent = (fileName: string): string => {
    const findInTree = (nodes: FileNode[]): string | null => {
      for (const node of nodes) {
        if (node.type === 'file' && node.name === fileName) {
          return node.content || ''
        }
        if (node.children) {
          const found = findInTree(node.children)
          if (found !== null) return found
        }
      }
      return null
    }
    return findInTree(fileTree) || '// Select a file to view its contents'
  }

  const handleRun = async () => {
    setIsRunning(true)
    setTerminalOutput(prev => [...prev, '$ npm run build', 'Creating optimized production build...'])

    await new Promise(resolve => setTimeout(resolve, 1500))
    setTerminalOutput(prev => [...prev, '✓ Compiled successfully', '✓ Linting and checking validity...'])

    await new Promise(resolve => setTimeout(resolve, 1000))
    setTerminalOutput(prev => [...prev, '✓ Build completed!', '$'])
    setIsRunning(false)
  }

  const renderFileTree = (nodes: FileNode[], basePath = ''): React.ReactNode => {
    return nodes.map((node) => {
      const path = basePath ? `${basePath}/${node.name}` : node.name
      const isExpanded = expandedFolders.has(path)
      const isSelected = selectedFile === node.name

      if (node.type === 'folder') {
        return (
          <div key={path}>
            <button
              onClick={() => toggleFolder(path)}
              className="flex items-center gap-1 w-full px-2 py-1 text-sm hover:bg-muted rounded text-left"
            >
              {isExpanded ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
              <FolderTree className="h-4 w-4 text-yellow-500" />
              <span>{node.name}</span>
            </button>
            {isExpanded && node.children && (
              <div className="ml-4">
                {renderFileTree(node.children, path)}
              </div>
            )}
          </div>
        )
      }

      return (
        <button
          key={path}
          onClick={() => setSelectedFile(node.name)}
          className={`flex items-center gap-1 w-full px-2 py-1 text-sm rounded text-left ${
            isSelected ? 'bg-primary/10 text-primary' : 'hover:bg-muted'
          }`}
        >
          <FileCode className="h-4 w-4 text-blue-500 ml-5" />
          <span>{node.name}</span>
        </button>
      )
    })
  }

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-[50vh]">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    )
  }

  if (!projectId) {
    return (
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <Link href="/dashboard/pipeline">
            <Button variant="ghost" size="icon">
              <ArrowLeft className="h-4 w-4" />
            </Button>
          </Link>
          <div>
            <h2 className="text-2xl font-bold tracking-tight">Dev Dude</h2>
            <p className="text-muted-foreground">
              Interactive development environment with live preview
            </p>
          </div>
        </div>

        <Card>
          <CardHeader>
            <div className="flex items-center gap-3">
              <div className="p-3 rounded-lg bg-yellow-100">
                <AlertCircle className="h-6 w-6 text-yellow-600" />
              </div>
              <div>
                <CardTitle>No Project Selected</CardTitle>
                <p className="text-sm text-muted-foreground">
                  Complete the earlier pipeline steps first
                </p>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <Link href="/dashboard/pipeline/preset">
              <Button>
                Start with Preset Dude
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </Link>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link href="/dashboard/pipeline">
          <Button variant="ghost" size="icon">
            <ArrowLeft className="h-4 w-4" />
          </Button>
        </Link>
        <div className="flex-1">
          <h2 className="text-2xl font-bold tracking-tight">Dev Dude</h2>
          <p className="text-muted-foreground">
            Interactive development environment for {project?.name}
          </p>
        </div>
        <Link href={`/dashboard/pipeline/deploy?project=${projectId}`}>
          <Button>
            Continue to Deploy
            <ArrowRight className="ml-2 h-4 w-4" />
          </Button>
        </Link>
      </div>

      <div className="grid gap-4 lg:grid-cols-4">
        {/* File Explorer */}
        <Card className="lg:col-span-1">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Explorer</CardTitle>
          </CardHeader>
          <CardContent className="p-2">
            <div className="text-sm">
              {renderFileTree(fileTree)}
            </div>
          </CardContent>
        </Card>

        {/* Code Editor */}
        <Card className="lg:col-span-2 lg:row-span-2">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-base">
                {selectedFile || 'Code Editor'}
              </CardTitle>
              <div className="flex gap-2">
                <Button variant="ghost" size="sm" onClick={handleRun} disabled={isRunning}>
                  {isRunning ? (
                    <Loader2 className="h-4 w-4 mr-1 animate-spin" />
                  ) : (
                    <Play className="h-4 w-4 mr-1" />
                  )}
                  {isRunning ? 'Building...' : 'Run'}
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <div className="rounded-lg bg-zinc-900 text-zinc-100 p-4 font-mono text-sm h-[400px] overflow-auto">
              <pre className="whitespace-pre-wrap">
                {selectedFile ? findFileContent(selectedFile) : (
                  <>
                    <div className="text-zinc-500">{'// Dev Dude - Interactive IDE'}</div>
                    <div className="text-zinc-500">{'// Select a file from the explorer to edit'}</div>
                    <br />
                    <div className="text-blue-400">import</div>
                    <span className="text-zinc-100">{" { useState } "}</span>
                    <span className="text-blue-400">from</span>
                    <span className="text-green-400">{" 'react'"}</span>
                    <br /><br />
                    <div className="text-blue-400">export default function</div>
                    <span className="text-yellow-400"> App</span>
                    <span className="text-zinc-100">{"() {"}</span>
                    <br />
                    <span className="text-zinc-100">{"  "}</span>
                    <span className="text-blue-400">return</span>
                    <span className="text-zinc-100">{" ("}</span>
                    <br />
                    <span className="text-zinc-100">{"    <"}</span>
                    <span className="text-red-400">div</span>
                    <span className="text-zinc-100">{">"}</span>
                    <br />
                    <span className="text-zinc-100">{"      Hello DevDudes!"}</span>
                    <br />
                    <span className="text-zinc-100">{"    </"}</span>
                    <span className="text-red-400">div</span>
                    <span className="text-zinc-100">{">"}</span>
                    <br />
                    <span className="text-zinc-100">{"  )"}</span>
                    <br />
                    <span className="text-zinc-100">{"}"}</span>
                  </>
                )}
              </pre>
            </div>
          </CardContent>
        </Card>

        {/* Preview */}
        <Card className="lg:col-span-1">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-base">Live Preview</CardTitle>
              <Button variant="ghost" size="sm">
                <Eye className="h-4 w-4 mr-1" />
                Refresh
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            <div className="rounded-lg border bg-white h-[180px] flex items-center justify-center">
              <div className="text-center p-4">
                <p className="font-semibold">{project?.name}</p>
                <p className="text-sm text-muted-foreground">Preview will appear here</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Terminal */}
        <Card className="lg:col-span-1">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-base">Terminal</CardTitle>
              <Button variant="ghost" size="sm" onClick={() => setTerminalOutput(['$'])}>
                <Terminal className="h-4 w-4 mr-1" />
                Clear
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            <div className="rounded-lg bg-zinc-900 text-zinc-100 p-4 font-mono text-xs h-[180px] overflow-auto">
              {terminalOutput.map((line, i) => (
                <div key={i} className={line.startsWith('$') ? 'text-green-400' : line.startsWith('✓') ? 'text-green-400' : 'text-zinc-400'}>
                  {line}
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
