import { z } from 'zod'
import { ciConfigSchema, defaultCIConfig } from '@/lib/shared-pipeline/ci'
import type { WebsiteConfig } from '@/lib/website-pipeline/types'

export const websiteConfigSchema = z.object({
  // Step 1: Import
  importedProjectId: z.string().nullable().default(null),
  importMode: z.string().default(''),

  // Step 2: Website Type & Purpose
  websiteTypes: z.array(z.string()).default([]),
  industry: z.string().default(''),
  targetAudience: z.string().default(''),
  elevatorPitch: z.string().max(1000).default(''),
  siteName: z.string().max(200).default(''),

  // Step 3: Branding & Domain
  primaryColor: z.string().default('#6366f1'),
  secondaryColor: z.string().default('#ec4899'),
  fontHeading: z.string().default(''),
  fontBody: z.string().default(''),
  logoStyle: z.string().default(''),
  brandTone: z.string().default(''),
  customDomain: z.string().max(200).default(''),

  // Step 4: Corporate Identity
  corporateIdentity: ciConfigSchema.default(ciConfigSchema.parse({})),

  // Step 5: Layout & Navigation
  layoutStyle: z.string().default(''),
  navigationStyle: z.string().default(''),
  headerStyle: z.string().default(''),
  footerStyle: z.string().default(''),
  pageStructure: z.array(z.string()).default([]),

  // Step 5: Visual Design & Theme
  theme: z.string().default(''),
  designSystem: z.string().default(''),
  animationLevel: z.string().default(''),
  iconStyle: z.string().default(''),
  imageStrategy: z.string().default(''),
  borderRadius: z.string().default(''),

  // Step 6: Content Strategy
  contentTypes: z.array(z.string()).default([]),
  cmsProvider: z.string().default(''),
  blogEnabled: z.boolean().default(false),
  i18nEnabled: z.boolean().default(false),
  i18nLanguages: z.array(z.string()).default([]),
  searchEnabled: z.boolean().default(false),
  searchProvider: z.string().default(''),

  // Step 7: Framework & Stack
  framework: z.string().default(''),
  language: z.string().default('typescript'),
  styling: z.string().default(''),
  componentLibrary: z.string().default(''),
  packageManager: z.string().default(''),
  monorepo: z.boolean().default(false),

  // Step 8: Database & Backend
  database: z.string().default(''),
  orm: z.string().default(''),
  auth: z.string().default(''),
  authMethods: z.array(z.string()).default([]),
  storageProvider: z.string().default(''),
  apiStyle: z.string().default(''),

  // Step 9: Integrations & APIs
  emailProvider: z.string().default(''),
  analytics: z.array(z.string()).default([]),
  monitoring: z.string().default(''),
  crm: z.string().default(''),
  marketing: z.array(z.string()).default([]),
  chatWidget: z.string().default(''),

  // Step 10: Products & Catalog (conditional)
  productType: z.string().default(''),
  catalogSize: z.string().default(''),
  categories: z.boolean().default(true),
  variants: z.boolean().default(false),
  inventory: z.boolean().default(false),
  reviews: z.boolean().default(false),
  wishlist: z.boolean().default(false),
  compareProducts: z.boolean().default(false),

  // Step 11: Payments & Checkout (conditional)
  paymentProcessor: z.string().default(''),
  checkoutStyle: z.string().default(''),
  currencies: z.array(z.string()).default([]),
  taxCalculation: z.string().default(''),
  invoicing: z.boolean().default(false),
  subscriptionBilling: z.boolean().default(false),
  coupons: z.boolean().default(false),
  giftCards: z.boolean().default(false),

  // Step 12: Shipping & Fulfillment (conditional)
  shippingProviders: z.array(z.string()).default([]),
  fulfillment: z.string().default(''),
  internationalShipping: z.boolean().default(false),
  shippingZones: z.boolean().default(false),
  trackingEnabled: z.boolean().default(false),
  returnsPolicy: z.boolean().default(false),

  // Step 13: SEO & Analytics
  seoStrategy: z.string().default(''),
  structuredData: z.array(z.string()).default([]),
  sitemap: z.boolean().default(true),
  robotsTxt: z.boolean().default(true),
  openGraph: z.boolean().default(true),
  twitterCards: z.boolean().default(false),
  canonicalUrls: z.boolean().default(true),
  performanceBudget: z.string().default(''),

  // Step 14: Performance & Security
  ssl: z.boolean().default(true),
  csp: z.boolean().default(false),
  rateLimiting: z.boolean().default(false),
  ddosProtection: z.boolean().default(false),
  waf: z.boolean().default(false),
  backups: z.string().default(''),
  compliance: z.array(z.string()).default([]),
  cdn: z.string().default(''),
  caching: z.string().default(''),

  // Step 15: Hosting & Deployment
  hosting: z.string().default(''),
  ci: z.string().default(''),
  environments: z.array(z.string()).default([]),
  containerized: z.boolean().default(false),
  region: z.string().default(''),
  scaling: z.string().default(''),
  domainProvider: z.string().default(''),
  distributionChannels: z.array(z.string()).default([]),

  // Step 16: AI & Notes
  aiFeatures: z.array(z.string()).default([]),
  aiProvider: z.string().default(''),
  detailedDescription: z.string().default(''),
  targetPages: z.string().default(''),
  referenceWebsites: z.string().default(''),
  constraints: z.string().default(''),
  additionalNotes: z.string().default(''),

  // Step 17: Business Modules (conditional: business-service)
  businessModules: z.array(z.string()).default([]),
  adminFeatures: z.array(z.string()).default([]),
  formBuilderFeatures: z.array(z.string()).default([]),
  signatureLayouts: z.array(z.string()).default([]),
  signatureFeatures: z.array(z.string()).default([]),
  expenseFeatures: z.array(z.string()).default([]),
  budgetFeatures: z.array(z.string()).default([]),
  sickLeaveFeatures: z.array(z.string()).default([]),

  // Step 18: Directory & Messaging (conditional: business-service)
  directoryProvider: z.string().default(''),
  directorySyncFields: z.array(z.string()).default([]),
  directoryAutoSync: z.boolean().default(false),
  communicationChannels: z.array(z.string()).default([]),
  defaultNotifyChannel: z.string().default(''),
})

export const defaultWebsiteConfig: WebsiteConfig = {
  importedProjectId: null,
  importMode: '',
  websiteTypes: [],
  industry: '',
  targetAudience: '',
  elevatorPitch: '',
  siteName: '',
  primaryColor: '#6366f1',
  secondaryColor: '#ec4899',
  fontHeading: '',
  fontBody: '',
  logoStyle: '',
  brandTone: '',
  customDomain: '',
  corporateIdentity: defaultCIConfig,
  layoutStyle: '',
  navigationStyle: '',
  headerStyle: '',
  footerStyle: '',
  pageStructure: [],
  theme: '',
  designSystem: '',
  animationLevel: '',
  iconStyle: '',
  imageStrategy: '',
  borderRadius: '',
  contentTypes: [],
  cmsProvider: '',
  blogEnabled: false,
  i18nEnabled: false,
  i18nLanguages: [],
  searchEnabled: false,
  searchProvider: '',
  framework: '',
  language: 'typescript',
  styling: '',
  componentLibrary: '',
  packageManager: '',
  monorepo: false,
  database: '',
  orm: '',
  auth: '',
  authMethods: [],
  storageProvider: '',
  apiStyle: '',
  emailProvider: '',
  analytics: [],
  monitoring: '',
  crm: '',
  marketing: [],
  chatWidget: '',
  productType: '',
  catalogSize: '',
  categories: true,
  variants: false,
  inventory: false,
  reviews: false,
  wishlist: false,
  compareProducts: false,
  paymentProcessor: '',
  checkoutStyle: '',
  currencies: [],
  taxCalculation: '',
  invoicing: false,
  subscriptionBilling: false,
  coupons: false,
  giftCards: false,
  shippingProviders: [],
  fulfillment: '',
  internationalShipping: false,
  shippingZones: false,
  trackingEnabled: false,
  returnsPolicy: false,
  seoStrategy: '',
  structuredData: [],
  sitemap: true,
  robotsTxt: true,
  openGraph: true,
  twitterCards: false,
  canonicalUrls: true,
  performanceBudget: '',
  ssl: true,
  csp: false,
  rateLimiting: false,
  ddosProtection: false,
  waf: false,
  backups: '',
  compliance: [],
  cdn: '',
  caching: '',
  hosting: '',
  ci: '',
  environments: [],
  containerized: false,
  region: '',
  scaling: '',
  domainProvider: '',
  distributionChannels: [],
  aiFeatures: [],
  aiProvider: '',
  detailedDescription: '',
  targetPages: '',
  referenceWebsites: '',
  constraints: '',
  additionalNotes: '',
  businessModules: [],
  adminFeatures: [],
  formBuilderFeatures: [],
  signatureLayouts: [],
  signatureFeatures: [],
  expenseFeatures: [],
  budgetFeatures: [],
  sickLeaveFeatures: [],
  directoryProvider: '',
  directorySyncFields: [],
  directoryAutoSync: false,
  communicationChannels: [],
  defaultNotifyChannel: '',
}
